name: Build Windows EXE
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller reportlab pandas PySide6 arabic-reshaper python-bidi openpyxl

      - name: Build (one-file)
        shell: cmd
        run: >
          pyinstaller --noconfirm --onefile
          --hidden-import reportlab.graphics.barcode.code128
          --hidden-import arabic_reshaper
          --hidden-import bidi.algorithm
          --collect-submodules PySide6
          --collect-data reportlab
          --add-data "templates;templates"
          --add-data "fonts;fonts"
          allappfinal27.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: CreatePriceLabels-Windows
          path: dist/*.exe
